# Data parameters
data:
    dataset: cifar10
    data_dir: data/cifar10-data
    input_size: [32,32]
    input_channels: 3
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: trained_model/cifar/vgg16
    task: classification
    learner: default
    nb_epochs: 400
    batch_size: 128
    loss:
        name: cross_entropy
    optimizer:
        name: adam
        lr: 0.001
    lr_schedule:
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: False
    num_workers: 3
    augmentations:
        hflip: True
        rotate: 15
        normalize: [[0.4914, 0.4822, 0.4465], [0.2023, 0.1994, 0.2010]]

# Model parameters
model:
    name: vgg16
    resume: vgg16

